import Vue from 'vue'
import Unicon from 'vue-unicons'
import {
  uniApps,
  uniArrowRight,
  uniCalendarAlt,
  uniPlus,
  uniListUl,
  uniFile,
  uniFileAlt,
  uniEllipsisH,
  uniEllipsisV,
  uniLayerGroup,
  uniEditAlt,
  uniPhone,
  uniPolygon,
  uniPaperclip,
  uniSave,
  uniCube,
  uniSetting,
  uniSlidersVAlt,
  uniSlidersV,
  uniSuitcase,
  uniTimes,
  uniUser,
  uniUserSquare,
  uniUserArrows,
  uniUsersAlt,
} from 'vue-unicons/src/icons'

Unicon.add([
  uniApps,
  uniArrowRight,
  uniCalendarAlt,
  uniPlus,
  uniListUl,
  uniFile,
  uniFileAlt,
  uniEllipsisH,
  uniEllipsisV,
  uniLayerGroup,
  uniEditAlt,
  uniPhone,
  uniPolygon,
  uniPaperclip,
  uniSave,
  uniCube,
  uniSetting,
  uniSlidersVAlt,
  uniSlidersV,
  uniSuitcase,
  uniUser,
  uniUserSquare,
  uniTimes,
  uniUserArrows,
  uniUsersAlt,
])
Vue.use(Unicon)
